.TH someblocks 1 someblocks\-1.0
.SH NAME
someblocks \- Modular status bar for somebar
.SH SYNOPSIS
.B someblocks
.RB [ \-d
.IR delimiter ]
.RB [ \-s
.IR path ]
.RB [ \-p ]
.SH DESCRIPTION
Modular status bar for somebar written in c.
.SH OPTIONS
.TP
.B \-d
Sets the delimiter between blocks
.TP
.B \-s
Sets the path to the somebar control FIFO. The default value is
$XDG_RUNTIME_DIR/somebar-0
.TP
.B \-p
Sends output to stdout instead of somebar
.SH BUGS
Send bug reports to ~raphi/public-inbox@lists.sr.ht
